 name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2
        with:
          github_user_name: SumeyraBayrak
          outputs: dist/snake.svg

      - name: Upload Snake
        uses: actions/upload-artifact@v3  # Artifaktı yükle
        with:
          name: contribution-snake
          path: dist/snake.svg # Yükleme yapılacak dosyanın yolu
